### ISSUE TITLE
PSWeights are not stored in a coherent way

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/cmssw#381] opened 2019-06-24 09:24 UTC
it seems we are not storing coherently the PSWeights.
Despite the doc saying "PS weights (w_var / w_nominal)" sometimes the ratio is not ~1.

This seems to be due to the fact that at 
https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L244

we divide by w0 being defined as lheProd.originalXWGTUP() that is not always the same as 
genProd->weight() (aka weights[0]) (see below for two examples from different files in 2017 and 18 campaigns)
It would be probably safe to divide by weights[0] or by weight().
@adewit @gpetruc any opinion?

root [11] Events->Scan("PSWeight:LHEWeight_originalXWGTUP:genWeight")
***********************************************************
Row Instance PSWeight LHEWeight genWeight 
***********************************************************
0 0 277.03125 0.0033976 1 
0 1 186.36718 0.0033976 1 
0 2 306.15625 0.0033976 1 
0 3 333.5 0.0033976 1 
1 0 323.45312 0.0033976 1 
1 1 379.5 0.0033976 1 
1 2 267.32812 0.0033976 1 
1 3 223.5625 0.0033976 1 
2 0 283.29687 0.0033976 0.9900000

vs 

root [1] Events->Scan("PSWeight:LHEWeight_originalXWGTUP:genWeight")
***********************************************************
    Row    Instance   PSWeight  LHEWeight  genWeight 
***********************************************************
        0         0  0.9359436  13.021485  13.021485 
        0         1  0.8313598  13.021485  13.021485 
        0         2  1.0455322  13.021485  13.021485

**Comment by peruzzim** [comment] 2019-06-24 11:28
@epalencia did you meet this issue when looking at PS weights for #330?

**Comment by epalencia** [comment] 2019-06-24 12:36
As far as I know, lheProd.originalXWGTUP() is the correct parameter to normalize. And this is somehow documented here: https://twiki.cern.ch/twiki/bin/view/CMS/TopModGen#Event_Generation

-----------------------------------------------------------------------------------------------------------------
Please note that there's a 1-2% mismatch in about 20% events for the nominal value seen from PS reweighing (identical to LHE generator originalXWGTUP weight) w.r.t. the nominal ME muR=muF=1 due to rounding in the reweighing. I.e.

 LHEEventProduct_externalLHEProducer__SIM.obj.originalXWGTUP()  = GenEventInfoProduct_generator__SIM.obj.weights_[0]  

which may differ 1-2% from

  LHEEventProduct_externalLHEProducer__SIM.obj.weights().wgt[0] 

So, always rescale to the original value, to take into account this 1-2% mismatching, as recommended here
-----------------------------------------------------------------------------------------------------------------

**Comment by arizzi** [comment] 2019-06-24 13:44
you may have missed that the value is off by a factor 300.
I doubt that the effect of PS weights is to change the cross section of such factor :-)

**Comment by epalencia** [comment] 2019-06-24 13:54
No I didn't :) . Could you send me the file used so I can try to have a look? I will also report it to TMG. And what is the difference between the two set of numbers you sent?

**Comment by gmandorl** [comment] 2019-06-24 14:01
/EWK_LLJJ_MLL-50_MJJ-120_TuneCP5_PSweights_13TeV-madgraph-pythia8/RunIIFall17NanoAODv4-PU2017_12Apr2018_Nano14Dec2018_102X_mc2017_realistic_v6-v1/NANOAODSIM
/LLJJ_INT_SM_5f_LO_TuneCP5_PSweights_13TeV_madgraph-pythia8/RunIIFall17NanoAODv4-PU2017_12Apr2018_Nano14Dec2018_102X_mc2017_realistic_v6-v1/NANOAODSIM

**Comment by epalencia** [comment] 2019-06-24 14:04
I'm sorry but I might need a bit of explanation... The two set of numbers correspond to two different files? If that is the case, EWK_LLJJ is the one with weights around 300 and LLJJ_INT the one with weights around 1?

**Comment by arizzi** [comment] 2019-06-24 14:13
just take one of the two, e.g. EWK_LLJJ.

Weights are around 300 because we divide by originalXWGTUP() rather than by weights[0]  and you claimed that this is the right choice.

**Comment by epalencia** [comment] 2019-06-24 14:17
PSweight in the second Scan is different from PSweight in the first Scan?

**Comment by arizzi** [comment] 2019-06-24 14:19
they are two different files... one where genWeight = originalXWGTUP() and the other where they differ

**Comment by epalencia** [comment] 2019-06-24 14:59
I have been able to reproduce your first set of numbers using this file /eos/cms/store/mc/RunIIFall17NanoAODv4/EWK_LLJJ_MLL-50_MJJ-120_TuneCP5_PSweights_13TeV-madgraph-pythia8/NANOAODSIM/PU2017_12Apr2018_Nano14Dec2018_102X_mc2017_realistic_v6-v1/70000/E7BA2ADC-F913-3242-9963-1D3285278DA5.root: PSweights are around 290, LHEWeight_originalXWGTUP around 0.0034 and genWeight around 1.

What I do not understand is why LHEWeight_originalXWGTUP and genWeight are so different for some datasets while they are similar for others. As I said, I'll report in TMG and post here the outcome.

**Comment by agrohsje** [comment] 2019-06-24 22:48
Let me add one comment. genWeight should be a vector that comes from P8 and contains the PS weights and the nominal PS weight (1 or 0.999) plus one additional entry at first place, which is the nominal PS weight * hadronization eff. For some process we evaluate this number (suc. had/total trials of hadr.) and multiply it with the default PS weight from Py8. So the order is 
PS weight * eff ; PS weights; PS var1 ; PS var 2.  On top, for some samples, the genweight includes a multiplicative factor from the default lhe weight, which is most of the time originalxwgtup. 
It would be interesting to understand for which samples the lheweight gets picked up and whether this happens in P8 or CMSSW. I don't know at the moment.
@epalencia if you are stuck let me know.

**Comment by NJManganelli** [comment] 2019-06-25 16:47
Considering the shift to using weights in place of dedicated samples for 2017 and 2018, is there a comprehensive list of resources for analyzers to use when accessing and applying weights?

**Comment by arizzi** [comment] 2019-06-26 07:35
btw for 2018 in most of the samples I've seen there are no PSWeights... is that expected?

**Comment by epalencia** [comment] 2019-06-26 07:53
Yes, there was a bug. This should be fixed in v5 production. More details here https://github.com/cms-nanoAOD/cmssw/issues/330.

**Comment by epalencia** [comment] 2019-06-26 13:52
Does anyone know why here

https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L244

PS weights are divided by w0 (lheProd.originalXWGTUP()) while here

https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L276

genWeight is used?

**Comment by adewit** [comment] 2019-06-26 14:03
The second case is only called if there are no LHE weights (ie there is no lheProd.originalXWGTUP() to divide by).

**Comment by arizzi** [comment] 2019-06-26 14:06
I fail to understand one thing, given that central values that people use is with genWeight (at least when not using PSWeights at all), shouldn't the ratio simply be against genWeight?

**Comment by adewit** [comment] 2019-06-26 14:16
Yes, if the PS weight variations are effectively multiplied by genWeight, which Alexander's message above suggests is the case. I think when working on this implementation I also followed the instructions in the twiki linked from this comment: https://github.com/cms-nanoAOD/cmssw/issues/381#issuecomment-504990973 , and it so happened to be that the sample I tested on had lheProd.originalXWGTUP() = genWeight, such that everything looked like it was working correctly

**Comment by agrohsje** [comment] 2019-07-09 16:11
dear @adewit @epalencia @arizzi : there seems some confusion. let me try to clarify. i hope i can write it up such that it is easy to understand. we can also have a direct chat if that is helpful.
the genweight vector is the weight vector (pythia.info.weight()) that comes  from pythia 8. there is 1 additional entry at the first position which we add in cms and this is the first pythia 8 weight * hadronization efficiency or times the  ckkw/umeps/unlops merging weight.
now the question is what does pythia 8 provide as weight? this depends on a parameter in the lhe file it reads in, i.e. it depends on IDWTUP (see  void LHAup::setStrategy( int strategy)  on http://home.thep.lu.se/~torbjorn/pythia82html/LesHouchesAccord.html for more details ). For LO samples, this is often 3, so the pythia 8 weight will not include the LHE weight. If it is e.g. 4 or -4, it will be included.

**Comment by kpedro88** [comment] 2019-07-30 13:54
Relevant note for this issue: @kdlong is trying to implement smarter storage of weights at the GEN level, which would hopefully make it much easier for nanoAOD to pick out the values it wants to store. This is aimed at the UL samples.

**Comment by arizzi** [comment] 2019-09-19 07:58
not sure what is the conclusion here
@agrohsje  I'm not sure I understand from your last message how it clarifies what we need to use.
@kpedro88 while fix it for next campaigns, we have to handle existing MC samples and we may want to fix it for next nano processing. 

I'd suggest in nanoaod to always divide by weight[0] aka weight() aka genWeight() rather than originalXWGTUP ... any reason not to do so?

**Comment by kdlong** [comment] 2019-09-20 22:08
First I have to say I'm still totally confused by what is stored in NanoAOD in many cases, and also in what the optimal storage would be for the PS weights. @agrohsje did we ever discuss this in a GEN meeting?

@arizzi, the approach we're working on (@kpedro88, me, @dteague) is to add a new GenWeightProduct/GenWeightInfoProduct to the event that contain the metaInfo about the weights, parsed from the LHE or GEN and stored in the run, and then the weights per event stored in a way that the order (and association to groups/types) is guaranteed to match the metaInfo stored in the run. More info here: https://indico.cern.ch/event/841561/#3-update-on-generator-weight-m

Ideally this should be run at the GEN step, to drop the weight values (and their IDs, which are no very useful) from the GenInfoProduct and to parse the weights one time only. But, it is quite straightforward to also have a producer that runs on MiniAOD (or before) and produces the same products. There's a bit of inefficiency in reorganizing the weights per event, but it could be plugged into the NanoAOD workflow directly. 

What's the timeline for the next reprocessing? We have a structure of the products implemented, mostly the parsing needs to be expanded and then it needs to be rigorously tested. It's already gone much slower than I had hoped but with focused effort it could converge in a couple of weeks.

**Comment by arizzi** [comment] 2019-09-21 06:14
it doesn't necessarily  need to be per event in nanoaod as nanoaod also have the run branch... on the other hand if 90% of the analysis are going to use the events in the same N ways we can just make easy to to so (e.g. if most of the analysis just use the various weights to compute central values, ISR/FSR up/dow, PDF up/down, Ren/Fact up/down let's be sure that it is easy to compute those variations)

**Comment by kdlong** [comment] 2019-09-21 12:43
@arizzi right, you don't need ID per event. That's why we propose restructuring the even information. In order to do this, you need to process each event (such that std::vector<WeightsInfo> --> std::vector<float> from the exisiting GenInfoProduct to the proposed GenWeightInfoProduct. At GEN you're processing the info from the LHE anyway, so you can fill whatever format you like. As a producer running on MiniAOD, you need to process event by event to change the structure. It's inefficient but it's best way to ensure common code can be used for both.

Do we already have tools for calculating the uncertainties in NanoAOD? If the weights are stored in a coherent and reliable way then can't the nanoaod tools have scripts to form the up/down variations from them? The way I've done this in my analysis setup is to produce 2D histograms of distributation vs. LHE weights with hist->Fill(var, i, weight*LHEweight[i]) and then have scripts  that form calculate uncertainties from all the 1D projections: https://github.com/kdlong/VVAnalysis/blob/CombineRefactor/Utilities/python/HistTools.py#L117-L210

If nothing better already exists something like this can be adapted, but I still see the most pressing issue to be a clear picture of which weight is which.

**Comment by arizzi** [comment] 2019-09-21 13:52
NB: in nanoaod, what is what, is written in the doc string

**Comment by kdlong** [comment] 2019-09-21 14:53
For the LHE/Gen weights in particular I find the doc string pretty far from self explanatory and had to dig into the code to find which sets are stored and how that's chosen.

**Comment by kdlong** [comment] 2019-09-21 15:09
Ok maybe that's an overstatement, the doc string itself is clear, but how the information is chosen and whether it's correct is not.

**Comment by swertz** [comment] 2019-10-15 09:59
What is the status of this? Going through this thread there is quite some confusion as to what weights should be used...

Is it correct to:
- use `genWeight` to fill the nominal histograms
- use `genWeight * altWeight[i]` for the variations (where `altWeight` is any of `LHEScaleWeight`, `LHEPdfWeight`, `PSWeight`)

**Closed as completed** 2020-03-13 14:05 UTC
Labels: bugfix
